# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-18 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10)),
                ('apellido', models.CharField(max_length=10)),
                ('correo', models.CharField(max_length=200)),
                ('contrasena', models.CharField(max_length=10)),
            ],
        ),
    ]
